// ⚠️ AUTO-GENERATED by gen_mcp_types.ts — DO NOT EDIT
// 运行 npm run mcp:fetch-tools 后执行 npm run mcp:gen-types 重新生成

import { mcpClient } from './client';

export interface DashGenericSearchResponse<T> {
  items: T[];
  status: number;
  total: number;
}

export interface DashGenericGetResponse<T> {
  item?: T;
  status: number;
}

export interface AssistaidialoguesUpsertOutput {
  status: number;
  error?: string;
  asker_id?: number;
  id?: number;
  scene?: string;
}

export interface AssistchatUpsertOutput {
  status: number;
  error?: string;
  asker_id?: number;
  assist_ai_dialogues_id?: number;
  id?: number;
}

export interface AuthGetUserTokenWithTokenV2Output {
  status: number;
  error?: string;
  token?: string;
}

export interface AuthRequestLoginTokenOutput {
  status: number;
  error?: string;
  token?: string;
}

export interface AuthRequestLoginTokenV2Output {
  status: number;
  error?: string;
  account?: string;
  token?: string;
}

export interface CreateCepingOutput {
  status: number;
  error?: string;
  client_id?: number;
  ceping_id?: number;
}

export interface CreateGaokaoCepingOutput {
  status: number;
  error?: string;
  client_id?: number;
  ceping_id?: number;
}

export interface CrmclientGaokao2CepingListOutput {
  status: number;
  client_id?: number;
  items?: null | {
      id: number;
    name: string;
    url?: string
  }[];
  urls?: null | string[];
}

export interface CrmclientUpdateProfileOutput {
  status: number;
  error?: string;
  client_id?: number;
  key?: string;
  saved_id?: number;
}

export interface DashGenericAllowPermissionTagsOutput {
  status: number;
  error?: string;
  allowPermissionTags?: null | string[];
}

export interface DashGenericFieldsOutput {
  status: number;
  rawFieldInfo?: string;
  error?: string;
  fields?: null | {
      field_path: string;
    field_type: string;
    label?: string;
    description?: string;
    is_relation: boolean;
    relation_model?: string
  }[];
}

export interface DashGenericGetModelListOutput {
  status: number;
  error?: string;
  models?: null | {
      name: string;
    display_name: string;
    description?: string
  }[];
}

export interface DashGenericSaveOutput {
  status: number;
  error?: string;
  id?: number;
}

export interface FileUploadOutput {
  status: number;
  id?: number;
  uri?: string;
  name?: string;
  error?: string;
}

export interface GetMyFileOutput {
  status: number;
  error?: string;
  folder?: null | {
      id: number;
    name: string;
    parent_id?: number;
    system?: boolean;
    size?: number;
    fileList?: null | {
          name: string;
      type: string;
      id: number;
      origin_filename?: string;
      content?: string;
      size?: number;
      if_has_index?: null | boolean;
      index_fail_count?: number
    }[];
    children?: null | unknown[]
  };
  needUpdate?: boolean;
  spaceFull?: boolean;
  rootFolderId?: number;
  defaultFolderId?: number;
}

export interface RepositoryFileManageOutput {
  status: number;
  error?: string;
  id?: number;
}

export interface RepositoryFolderManageOutput {
  status: number;
  error?: string;
  id?: number;
}

export interface ServiceActivationCodeOutput {
  status: number;
  error?: string;
  message?: string;
}

export interface ThirdPartyUserServiceInfoOutput {
  status: number;
  error?: string;
  user_id?: string;
  available_times?: number;
  end_time?: string;
}

export interface UserClientProfileIdOutput {
  status: number;
  error?: string;
  uid?: number;
  client_id?: number;
}

export interface UserLoginByPhoneOutput {
  status: number;
  error?: string;
  token?: string;
  is_register?: string;
}

export interface UserMeOutput {
  status: number;
  error?: string;
  me?: null | {
      uid: number;
    name: string;
    display_name?: string;
    nickname?: string;
    email?: string;
    phone?: string;
    avatar?: string;
    default_identity_id?: number;
    is_impersonating?: boolean;
    user_org?: string;
    user_org_default_language?: string
  };
}

export interface UserSendLoginSmsCodeOutput {
  status: number;
  error?: string;
}

export interface WeworkGetTokenOutput {
  status: number;
  error?: string;
  token?: string;
}

export interface XiaofangKnowledgeSearchOutput {
  status: number;
  error?: string;
  uid?: number;
  client_id?: number;
  apiStatus?: string;
  kind?: string;
  message?: null | {
      user: boolean;
    chat_bot: boolean;
    tstamp: string
  };
  relevantDocuments?: null | {
      metadata: {
          source: string;
      index_key: string
    };
    doc_content: string
  }[];
}

export interface ZhijiCompanionManageOutput {
  status: number;
  error?: string;
  id?: number;
  companion?: null | {
      id: number;
    name: string;
    description?: string;
    data?: string;
    avatar_ids?: null | number[];
    repository_ids?: null | number[];
    public: boolean
  };
}

export interface AssistRepositorySearchInput {
  /** 搜索关键词 */
  /** @example `"高考志愿填报"` */
  query?: string;
  /** 分类ID列表 */
  type_ids?: null | number[];
  /** 场景key，可选值：higher_education, personal, organizational */
  scene_key?: null | string[];
  /** 类型key */
  kind_key?: null | string[];
  /** 分类key */
  category_key?: string;
  /** 团队栏目 */
  label_key?: null | string[];
  /** 检索位置：common(公共), person(个人), org(团队) */
  /** @example `"common"` */
  location?: string;
  /** 发布开始时间，格式：2006-01-02 15:04:05 */
  published_start_time?: string;
  /** 发布结束时间，格式：2006-01-02 15:04:05 */
  published_end_time?: string;
  /** 创建开始时间，格式：2006-01-02 15:04:05 */
  release_start_time?: string;
  /** 创建结束时间，格式：2006-01-02 15:04:05 */
  release_end_time?: string;
  /** 筛选模块 */
  selected_modules_only?: null | string[];
  /** 排序字段：published_date, release_date。默认创建时间降序 */
  sortby?: string;
  /** 分页偏移量，默认0 */
  /** @example `0` */
  offset?: number;
  /** 每页数量，默认10 */
  /** @example `10` */
  size?: number;
}

export interface AssistaidialoguesUpsertInput {
  /** Record id. If omitted, creates a new record; if provided, updates the existing record. */
  id?: null | number;
  /** Soft delete flag. If true, marks the record as deleted. */
  deleted?: null | boolean;
  /** Dialogue name (required when creating). Will be mapped to model field title. */
  /** @example `"我的第一次对话"` */
  name?: null | string;
  /** Additional information JSON string. Validated as JSON. */
  /** @example `"{"foo": "bar"}"` */
  additional_information?: string;
}

export interface AssistchatUpsertInput {
  /** Record id. If omitted, creates a new record; if provided, updates the existing record. */
  id?: null | number;
  /** Soft delete flag. If true, marks the record as deleted. */
  deleted?: null | boolean;
  /** Optional display name. If ask is empty, uses name as ask. */
  name?: string;
  /** User question (required when creating). If empty, falls back to name. */
  /** @example `"你是谁？"` */
  ask?: null | string;
  /** AI answer JSON string (required when creating). Validated as JSON. */
  /** @example `"{"answer":"我是AI"}"` */
  ai_data?: null | string;
  /** Existing dialogue id. If omitted, creates a new dialogue. */
  assist_ai_dialogues_id?: number;
  /** Dialogue name when auto-creating a new dialogue. Default: name or ask. */
  dialogue_name?: string;
}

export interface AuthGetUserTokenWithTokenV2Input {
  /** Account (required) */
  /** @example `"demo@example.com"` */
  account: string;
  /** Login token (required) */
  /** @example `"abc123xyz"` */
  token: string;
}

export interface AuthRequestLoginTokenInput {
  /** Account (required) */
  /** @example `"demo@example.com"` */
  account: string;
  /** Password (required) */
  /** @example `"password123"` */
  password: string;
}

export interface CreateCepingInput {
  /** 测评类型，如 course_planning, fos, career_gaokao, career_orientation, professional_inclination, holland_career_interest, mbti_personality, gaokao2 等 */
  /** @example `"course_planning"` */
  kind: string;
}

export interface CreateGaokaoCepingInput {
  /** 高考分数 */
  /** @example `600` */
  ncee_score: number;
  /** 选科，可选值：物理、化学、生物、历史、地理、思想政治 */
  /** @example `["物理","化学","生物"]` */
  elective_subjects: null | string[];
  /** 报考批次，例如 本科普通批 */
  /** @example `"本科普通批"` */
  bkpc: string;
  /** 位次 */
  /** @example `22548` */
  precedence: number;
}

export interface CrmclientUpdateProfileInput {
  /** Field key to update. Allowed: gaokao_year, gaokao_province, zhi_ji_personal_resume */
  /** @example `"gaokao_year"` */
  key: string;
  /** JSON string containing the key/value to update. id is auto-injected from current user's client_id */
  /** @example `"{"gaokao_year":"2026"}"` */
  values: string;
}

export interface DashGenericAllowPermissionTagsInput {
  /** Permission tags to match */
  /** @example `["permission_list.admin","can_edit_profile"]` */
  matchPermissionTags: null | string[];
}

export interface DashGenericFieldsInput {
  /** Dash model name, e.g. DashMenu */
  /** @example `"Application"` */
  model: string;
  /** Optional list of field paths. When empty, returns all fields info. */
  fields?: null | string[];
}

export interface DashGenericGetInput {
  /** Model name */
  /** @example `"DashMenu"` */
  model: string;
  /** Record ID (required by gql schema; pass 0 if only using floraExternalID) */
  /** @example `1` */
  id: number;
  /** Record flora external id */
  floraExternalID?: string;
  /** Returned field list */
  /** @example `["id","name"]` */
  fields?: null | string[];
  /** Record tags to match */
  matchRecordTags?: null | string[];
  /** Query tags */
  queryTags?: null | string[];
}

export interface DashGenericGetByFloraExternalIdInput {
  /** Model name */
  /** @example `"DashMenu"` */
  model: string;
  /** Record flora external id */
  /** @example `"DashMenu-1"` */
  floraExternalID: string;
  /** Returned field list */
  /** @example `["id","name"]` */
  fields?: null | string[];
  /** Record tags to match */
  matchRecordTags?: null | string[];
  /** Query tags */
  queryTags?: null | string[];
}

export interface DashGenericRelationModelSearchInput {
  /** Current model name */
  /** @example `"DashMenu"` */
  currentModel: string;
  /** Current record ID */
  /** @example `1` */
  currentID?: null | number;
  /** Current record external id */
  currentExternalID?: string;
  /** Relation field on current model */
  /** @example `"children"` */
  currentRelationField: string;
  /** Filter condition */
  /** @example `"{"logic_operator":"&","children":[{"leaf":{"field":"id","comparator":">","value":0}}]}"` */
  condition?: string;
  /** Returned field list */
  /** @example `["id","name"]` */
  fields?: null | string[];
  /** Data count limit. Default: 10, max: 100. */
  /** @example `10` */
  limit?: null | number;
  /** Pagination offset */
  /** @example `0` */
  offset?: null | number;
  /** Sort expression */
  /** @example `"[{"field":"id","order":"DESC"}]"` */
  sort?: string;
  /** Only supports 'associated' in MCP layer. Default: associated. */
  /** @example `"associated"` */
  searchType?: string;
  /** Record tags to match */
  matchRecordTags?: null | string[];
  /** Custom count fields */
  customCountFields?: string;
  /** Filter params JSON string */
  filterParams?: string;
  /** Whether to use tree table */
  treeTableUse?: null | boolean;
  /** Tree table parent field */
  treeTableParentField?: string;
  /** Tree table parent value */
  treeTableParentValue?: null | number;
  /** show_all_parents/show_all_childrens */
  treeTableMode?: string;
  /** Whether not to load page_info */
  notLoadPageInfo?: null | boolean;
  /** Query tags */
  queryTags?: null | string[];
}

export interface DashGenericSaveInput {
  /** Model name */
  /** @example `"Application"` */
  model: string;
  /** JSON string of values to save. Include 'id' for updates. */
  /** @example `"{"name": "New App", "description": "A new application"}"` */
  values: string;
  /** Current model name (parent) */
  currentModel?: string;
  /** Current record ID (parent) */
  currentID?: number;
  /** Current record external ID (parent) */
  currentExternalID?: string;
  /** Relation field on current model */
  currentRelationField?: string;
}

export interface DashGenericSearchInput {
  /** Model name */
  /** @example `"DashMenu"` */
  model: string;
  /** Filter condition */
  /** @example `"{"logic_operator":"&","children":[{"leaf":{"field":"id","comparator":">","value":0}}]}"` */
  condition?: string;
  /** Returned field list (required) */
  /** @example `["id","name"]` */
  fields: null | string[];
  /** Data count limit. Default: 10, max: 100. */
  /** @example `10` */
  limit?: number;
  /** Pagination offset */
  /** @example `0` */
  offset?: number;
  /** Sort expression */
  /** @example `"[{"field":"id","order":"DESC"}]"` */
  sort?: string;
  /** Whether to apply list view filter */
  applyListViewFilter?: null | boolean;
  /** Record tags to match */
  matchRecordTags?: null | string[];
  /** Current view config external id */
  viewConfigExternalID?: string;
  /** Custom count fields */
  customCountFields?: string;
  /** Whether to use tree table */
  treeTableUse?: null | boolean;
  /** Tree table parent field */
  treeTableParentField?: string;
  /** Tree table parent value */
  treeTableParentValue?: null | number;
  /** Whether not to load page_info */
  notLoadPageInfo?: null | boolean;
  /** Query tags */
  queryTags?: null | string[];
}

export interface FileUploadInput {
  /** Base64 encoded file content (required) */
  /** @example `"JVBERi0xLjQK..."` */
  fileContent: string;
  /** File name (required) */
  /** @example `"example.pdf"` */
  fileName: string;
  /** Whether the file is public. Default: false. */
  /** @example `true` */
  public?: null | boolean;
  /** External ID to associate with the file. */
  external_id?: string;
}

export interface RepositoryFileManageInput {
  /** Action: create, update, delete */
  /** @example `"create"` */
  action: string;
  /** File ID (required for update and delete) */
  id?: null | number;
  /** File name (optional for update and create) */
  /** @example `"new_file_name.pdf"` */
  name?: string;
  /** Target folder ID (optional for create, defaults to default knowledge base folder) */
  /** @example `null` */
  folder_id?: null | number;
  /** Blob ID for the file (required for create) */
  /** @example `12345` */
  blob_id?: null | number;
}

export interface RepositoryFolderManageInput {
  /** Action: create, update, delete */
  /** @example `"create"` */
  action: string;
  /** Folder ID (required for update and delete) */
  id?: null | number;
  /** Folder name (required for create and update) */
  /** @example `"新建文件夹"` */
  name?: string;
  /** Parent folder ID for new folder */
  /** @example `null` */
  parent_id?: null | number;
}

export interface ServiceActivationCodeInput {
  /** Activation code (required) */
  /** @example `"ABCD1234"` */
  code: string;
}

export interface ThirdPartyUserServiceInfoInput {
  /** Service ID (required) */
  /** @example `"abc123"` */
  service_id: string;
}

export interface UserLoginByPhoneInput {
  /** Phone number (required) */
  /** @example `"13800000000"` */
  phone: string;
  /** SMS code (required) */
  /** @example `"123456"` */
  code: string;
  /** Default: true. */
  autoRegister?: null | boolean;
  /** Default: true. */
  returnToken?: null | boolean;
}

export interface UserSendLoginSmsCodeInput {
  /** Phone number (required) */
  /** @example `"13800000000"` */
  phone: string;
  /** Area code / country code, optional */
  /** @example `"+86"` */
  area_code?: string;
}

export interface WeworkGetTokenInput {
  /** 用户名称 */
  /** @example `"张三"` */
  name: string;
  /** 企业微信用户ID */
  /** @example `"zhangsan"` */
  user_id: string;
}

export interface XiaofangKnowledgeSearchInput {
  /** Search query content (required) */
  /** @example `"高考志愿填报指南"` */
  content: string;
  /** Knowledge repository IDs to search in (required). */
  /** @example `[75]` */
  personalKnowledgeRepositoryIDs: null | number[];
}

export interface ZhijiCompanionManageInput {
  /** Action: create, update, get */
  /** @example `"create"` */
  action: string;
  /** Companion ID (required for update, get) */
  id?: null | number;
  /** Companion name (required for create) */
  /** @example `"我的数字分身"` */
  name?: string;
  /** Companion description */
  /** @example `"这是一个知己数字分身"` */
  description?: string;
  /** JSON string containing companion data (must be valid JSON) */
  /** @example `"{"key":"value"}"` */
  data?: string;
  /** List of avatar IDs to associate with this companion */
  /** @example `[1,2]` */
  avatar_ids?: null | number[];
  /** List of repository folder IDs from user's knowledge base */
  /** @example `[1,2]` */
  repository_ids?: null | number[];
  /** Whether the companion is public */
  /** @example `true` */
  public?: null | boolean;
}

/**
 * MCP 工具调用服务 — 所有方法均从 mcp_tools_list.json 自动生成。
 * 业务参数与基础设施参数（bearerToken / endpoint）分离。
 */
export class McpToolsService {
  private defaultBearerToken?: string;
  private defaultEndpoint?: string;

  constructor(options?: { bearerToken?: string; endpoint?: string }) {
    this.defaultBearerToken = options?.bearerToken;
    this.defaultEndpoint = options?.endpoint;
  }

  private invoke<T>(
    toolName: string,
    buildArgs: Record<string, unknown>,
  ): Promise<T> {
    // 数据平台场景：强制使用环境变量覆盖 bearerToken 和 endpoint
    if (this.defaultBearerToken !== undefined) {
      buildArgs = { ...buildArgs, bearerToken: this.defaultBearerToken };
    }
    if (this.defaultEndpoint !== undefined) {
      buildArgs = { ...buildArgs, endpoint: this.defaultEndpoint };
    }
    return mcpClient.callTool<T>(toolName, buildArgs as unknown as Record<string, unknown>);
  }

  /** 在知识库中进行统一搜索，支持关键词检索、场景/类型/分类过滤、时间范围筛选、团队栏目过滤等功能。 */
  async assistRepositorySearch<T = Record<string, unknown>>(
    params: AssistRepositorySearchInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<DashGenericSearchResponse<T>> {
    return this.invoke<DashGenericSearchResponse<T>>('assist_repository_search', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 创建或更新 AI 对话记录。自动使用当前用户 UID 作为 asker_id。 */
  async assistaidialoguesUpsert(
    params: AssistaidialoguesUpsertInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<AssistaidialoguesUpsertOutput> {
    return this.invoke<AssistaidialoguesUpsertOutput>('assistaidialogues_upsert', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 在 AI 对话会话中创建或更新聊天消息。 */
  async assistchatUpsert(
    params: AssistchatUpsertInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<AssistchatUpsertOutput> {
    return this.invoke<AssistchatUpsertOutput>('assistchat_upsert', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 将登录令牌兑换为用户 JWT 认证令牌。 */
  async authGetUserTokenWithTokenV2(
    params: AuthGetUserTokenWithTokenV2Input,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<AuthGetUserTokenWithTokenV2Output> {
    return this.invoke<AuthGetUserTokenWithTokenV2Output>('auth_get_user_token_with_token_v2', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 使用账号和密码请求登录令牌。 */
  async authRequestLoginToken(
    params: AuthRequestLoginTokenInput,
    endpoint?: string,
  ): Promise<AuthRequestLoginTokenOutput> {
    return this.invoke<AuthRequestLoginTokenOutput>('auth_request_login_token', {
      ...params,
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 为当前用户会话请求登录令牌（自动获取账号）。 */
  async authRequestLoginTokenV2(
    bearerToken?: string,
    endpoint?: string,
  ): Promise<AuthRequestLoginTokenV2Output> {
    return this.invoke<AuthRequestLoginTokenV2Output>('auth_request_login_token_v2', {
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 创建通用测评记录。 */
  async createCeping(
    params: CreateCepingInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<CreateCepingOutput> {
    return this.invoke<CreateCepingOutput>('create_ceping', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 创建高考志愿测评。 */
  async createGaokaoCeping(
    params: CreateGaokaoCepingInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<CreateGaokaoCepingOutput> {
    return this.invoke<CreateGaokaoCepingOutput>('create_gaokao_ceping', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 列出当前用户的测评记录列表。 */
  async crmclientGaokao2CepingList(
    bearerToken?: string,
    endpoint?: string,
  ): Promise<CrmclientGaokao2CepingListOutput> {
    return this.invoke<CrmclientGaokao2CepingListOutput>('crmclient_gaokao2_ceping_list', {
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 更新当前用户的个人资料信息。 */
  async crmclientUpdateProfile(
    params: CrmclientUpdateProfileInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<CrmclientUpdateProfileOutput> {
    return this.invoke<CrmclientUpdateProfileOutput>('crmclient_update_profile', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 判断当前用户是否拥有指定的权限标签。 */
  async dashGenericAllowPermissionTags(
    params: DashGenericAllowPermissionTagsInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<DashGenericAllowPermissionTagsOutput> {
    return this.invoke<DashGenericAllowPermissionTagsOutput>('dash_generic_allow_permission_tags', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 获取指定模型的字段信息（包括类型、标签、关联关系等）。 */
  async dashGenericFields(
    params: DashGenericFieldsInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<DashGenericFieldsOutput> {
    return this.invoke<DashGenericFieldsOutput>('dash_generic_fields', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 根据 ID 或外部 ID 获取指定模型的单条记录详情。 */
  async dashGenericGet<T = Record<string, unknown>>(
    params: DashGenericGetInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<DashGenericGetResponse<T>> {
    return this.invoke<DashGenericGetResponse<T>>('dash_generic_get', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 根据 Flora 外部 ID 获取指定模型的记录详情。 */
  async dashGenericGetByFloraExternalId<T = Record<string, unknown>>(
    params: DashGenericGetByFloraExternalIdInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<DashGenericGetResponse<T>> {
    return this.invoke<DashGenericGetResponse<T>>('dash_generic_get_by_flora_external_id', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 获取系统中所有可用的模型列表。 */
  async dashGenericGetModelList(
    bearerToken?: string,
    endpoint?: string,
  ): Promise<DashGenericGetModelListOutput> {
    return this.invoke<DashGenericGetModelListOutput>('dash_generic_get_model_list', {
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 搜索指定记录的关联模型数据（如子项、关联项等）。 */
  async dashGenericRelationModelSearch<T = Record<string, unknown>>(
    params: DashGenericRelationModelSearchInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<DashGenericSearchResponse<T>> {
    return this.invoke<DashGenericSearchResponse<T>>('dash_generic_relation_model_search', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 创建或更新模型记录。如果values中包含id则为更新操作，否则为创建操作。高危操作谨慎使用。 */
  async dashGenericSave(
    params: DashGenericSaveInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<DashGenericSaveOutput> {
    return this.invoke<DashGenericSaveOutput>('dash_generic_save', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 在指定模型中搜索记录，支持条件过滤、排序和分页。 */
  async dashGenericSearch<T = Record<string, unknown>>(
    params: DashGenericSearchInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<DashGenericSearchResponse<T>> {
    return this.invoke<DashGenericSearchResponse<T>>('dash_generic_search', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 将文件上传至系统存储。文件内容需经过 Base64 编码。 */
  async fileUpload(
    params: FileUploadInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<FileUploadOutput> {
    return this.invoke<FileUploadOutput>('file_upload', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 获取当前用户的个人知识库文件及文件夹结构。返回一个递归的文件夹树状结构（folder 字段）。每个文件夹包含 id, name, fileList (文件列表) 和 children (子文件夹列表)。文件对象包含 id, name, origin_filename, content, size 等。注意：该工具返回递归深度结构，请按需解析树形数据。 */
  async getMyFile(
    bearerToken?: string,
    endpoint?: string,
  ): Promise<GetMyFileOutput> {
    return this.invoke<GetMyFileOutput>('get_my_file', {
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 管理个人知识库文件（新建、修改、删除）。新建文件如未提供文件夹 ID，将默认存入默认知识库文件夹。 */
  async repositoryFileManage(
    params: RepositoryFileManageInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<RepositoryFileManageOutput> {
    return this.invoke<RepositoryFileManageOutput>('repository_file_manage', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 管理个人知识库文件夹（新建、修改、删除）。系统默认文件夹不可修改或删除。 */
  async repositoryFolderManage(
    params: RepositoryFolderManageInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<RepositoryFolderManageOutput> {
    return this.invoke<RepositoryFolderManageOutput>('repository_folder_manage', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 使用激活码激活服务。 */
  async serviceActivationCode(
    params: ServiceActivationCodeInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<ServiceActivationCodeOutput> {
    return this.invoke<ServiceActivationCodeOutput>('service_activation_code', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 获取用户的第三方服务信息。 */
  async thirdPartyUserServiceInfo(
    params: ThirdPartyUserServiceInfoInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<ThirdPartyUserServiceInfoOutput> {
    return this.invoke<ThirdPartyUserServiceInfoOutput>('third_party_user_service_info', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 获取当前用户的 Client Profile ID。 */
  async userClientProfileId(
    bearerToken?: string,
    endpoint?: string,
  ): Promise<UserClientProfileIdOutput> {
    return this.invoke<UserClientProfileIdOutput>('user_client_profile_id', {
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 通过手机验证码进行登录。 */
  async userLoginByPhone(
    params: UserLoginByPhoneInput,
    endpoint?: string,
  ): Promise<UserLoginByPhoneOutput> {
    return this.invoke<UserLoginByPhoneOutput>('user_login_by_phone', {
      ...params,
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 获取当前登录用户的个人信息。 */
  async userMe(
    bearerToken?: string,
    endpoint?: string,
  ): Promise<UserMeOutput> {
    return this.invoke<UserMeOutput>('user_me', {
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 向手机发送登录短信验证码。 */
  async userSendLoginSmsCode(
    params: UserSendLoginSmsCodeInput,
    endpoint?: string,
  ): Promise<UserSendLoginSmsCodeOutput> {
    return this.invoke<UserSendLoginSmsCodeOutput>('user_send_login_sms_code', {
      ...params,
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 根据企业微信用户ID和名称获取登录token。 */
  async weworkGetToken(
    params: WeworkGetTokenInput,
    endpoint?: string,
  ): Promise<WeworkGetTokenOutput> {
    return this.invoke<WeworkGetTokenOutput>('wework_get_token', {
      ...params,
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 在小方AI知识库中进行语义搜索。自动使用当前用户身份进行检索，支持指定知识库范围。 */
  async xiaofangKnowledgeSearch(
    params: XiaofangKnowledgeSearchInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<XiaofangKnowledgeSearchOutput> {
    return this.invoke<XiaofangKnowledgeSearchOutput>('xiaofang_knowledge_search', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

  /** 管理知己数字分身（新建、修改、查询）。支持设置名称、描述、数据详情及关联的知识库。 */
  async zhijiCompanionManage(
    params: ZhijiCompanionManageInput,
    bearerToken?: string,
    endpoint?: string,
  ): Promise<ZhijiCompanionManageOutput> {
    return this.invoke<ZhijiCompanionManageOutput>('zhiji_companion_manage', {
      ...params,
      ...(bearerToken ? { bearerToken } : {}),
      ...(endpoint ? { endpoint } : {}),
    });
  }

}

export const mcpTools = new McpToolsService();

/** 数据平台专用 MCP 工具实例，强制使用 VISIONSQUARE_DATA_HOST 作为 endpoint、VISIONSQUARE_AUTH_BEARER 作为 bearerToken */
export const mcpToolsDataPlatform = new McpToolsService({
  endpoint: process.env.VISIONSQUARE_DATA_HOST,
  bearerToken: process.env.VISIONSQUARE_AUTH_BEARER,
});
